---
- name: sysctl stuff
  hosts: all
  become: yes
  tasks:
    - name: Turn on ip forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        reload: yes
    - name: Modprobe br_netfilter
      community.general.modprobe:
        name: br_netfilter
        state: present
    - name: bridge-nf-call-iptables to 1
      ansible.posix.sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_set: yes
        reload: yes

- name: Disable SWAP
  hosts: all
  become: yes
  tasks:
    - name: Turn off swap
      shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

- name: Install containerd
  hosts: all
  become: yes
  tasks:
    - name: Install containerd
      ansible.builtin.apt:
        pkg:
          - containerd
        update_cache: yes

- name: Installing kubeadm, kubelet and kubectl
  hosts: all
  become: yes
  tasks:
    - name: Update and install prereqs
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        update_cache: yes
    - name: Add apt signing key for kubernetes
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add apt repository for kubernetes
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list
    - name: Install kubernetes binaries
      ansible.builtin.apt:
        state: present
        update_cache: yes
        pkg:
          - kubelet
          - kubeadm
          - kubectl
